apiVersion: apps/v1
kind: Deployment
metadata:
  name: pybo-web
  namespace: mysite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pybo-web
  template:
    metadata:
      labels:
        app: pybo-web
    spec:
      nodeSelector:
        role: web
      containers:
        - name: django
          image: jeegle16/django-pybo:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: pybo-web-svc
  namespace: mysite
spec:
  selector:
    app: pybo-web
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
