apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pybo-ingress
  namespace: mysite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: pybo.mysite.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pybo-web-svc
                port:
                  number: 8000
