apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysite
type: Opaque
stringData:
  mysql-root-password: pybo1234
  mysql-user: pybo
  mysql-password: pybo1234
  mysql-database: pybo


